---
name: Exception-Warning
version: 0.0401
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
abstract: Convert simple warn into real exception object
license: lgpl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Exception-Warning
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
  repository: http://dexter-cpan.googlecode.com/svn/Exception-Warning
build_requires:
  Test::Assert: 0.05
  Test::Unit::Lite: 0.12
  parent: 0
requires:
  Exception::Base: 0.21
  perl: 5.006
provides:
  Exception::Warning:
    file: lib/Exception/Warning.pm
    version: 0.0401
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
